In [8]:
import numpy as np

In [9]:
arr15 = np.arange(1, 10)

In [10]:
arr15

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Soma dos elementos 
np.sum(arr15)

45

In [12]:
# Produto dos elementos
np.prod(arr15)

362880

In [13]:
# Soma acumulada dos elementos
print(np.cumsum(arr15, dtype = float))
print(np.cumsum(arr15))

[ 1.  3.  6. 10. 15. 21. 28. 36. 45.]
[ 1  3  6 10 15 21 28 36 45]


In [14]:
# Criar 2 arrays

array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

In [15]:
# Soma dos arrays

arraySoma = np.add(array1, 90)
arraySoma2 = np.add(array1, array2)
print(arraySoma)
print(arraySoma2)

[91 92 93 94 95]
[ 7  9 11 13 15]


### Multiplicação de MATRIZES
Para multiplicar matrizes NumPy, podemos usar a função dot() ou o operador @. Ambos os métodos executam a multiplicação matricial. Importante lembrar que para a multiplicação de matrizes possa ser executada, o número de colunas da primeira matriz deve ser igual número de linhas da segunda matriz

In [16]:
# Criando matrizes
matriz1 = np.array([[1,2], [3,4]])
matriz2 = np.array([[5,6], [7,8]])

In [17]:
matriz1.shape

(2, 2)

In [18]:
matriz2.shape

(2, 2)

In [19]:
print(matriz1)

[[1 2]
 [3 4]]


In [20]:
print(matriz2)

[[5 6]
 [7 8]]


In [21]:
# Multiplicando matrizes

matrizMultiplica = np.dot(matriz1, matriz2)

In [22]:
print(matrizMultiplica)

[[19 22]
 [43 50]]


In [25]:
matrizMult2 = matriz1 @ matriz2 # Mesma coisa, multiplica matrizes
matrizMult2

array([[19, 22],
       [43, 50]])

# Slicing (Fatiamento) 

In [26]:
arr22 = np.diag(np.arange(3))

In [27]:
arr22

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [30]:
arr22[1,0]

0

In [34]:
arr22[:,2] # Qualquer linha e coluna 2

array([0, 0, 2])

In [36]:
arr23 = np.arange(10)
arr23

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#[inicio;final;salto]
arr23[2:9:2]

array([2, 4, 6, 8])

In [37]:
teste1 = np.array([1,2,3,4,5,6,7,8,9,10])
teste2 = np.array([11,1,2,3,6,5,4,8,9,7])

# Comparação item a item

teste1 == teste2

array([False, False, False, False, False, False, False,  True,  True,
       False])

In [38]:
# Comparação global

np.array_equal(teste1, teste2)

False

In [42]:
arr23.min()

0

In [43]:
arr23.max()

9

In [44]:
arraySomado = arr23 + 2

In [45]:
arraySomado

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
arrayFloat = np.array([1.5, 9.6, 5.8, 7.1,55.89, 7.78])

np.around(arrayFloat)

array([ 2., 10.,  6.,  7., 56.,  8.])

### flatten()

In [50]:
# "Achatando" uma matriz

matrizReal = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [52]:
print(matrizReal)

[[10 20 30 40]
 [50 60 70 80]]


In [56]:
np.ndim(matrizReal)

2

In [57]:
# Achatando

matrizAchatada = matrizReal.flatten()

In [59]:
print(matrizAchatada)

[10 20 30 40 50 60 70 80]


In [61]:
# Repetindo os elementos de array

np.repeat(matrizAchatada, 2)

array([10, 10, 20, 20, 30, 30, 40, 40, 50, 50, 60, 60, 70, 70, 80, 80])

In [62]:
# Repetindo todos os valores

np.tile(matrizAchatada, 3)

array([10, 20, 30, 40, 50, 60, 70, 80, 10, 20, 30, 40, 50, 60, 70, 80, 10,
       20, 30, 40, 50, 60, 70, 80])

In [63]:
arrayCopy = matrizReal

In [64]:
print(arrayCopy)

[[10 20 30 40]
 [50 60 70 80]]
