# NumPy

### https://numpy.org/

In [5]:
# Importando NumPy
import numpy as dsa

In [6]:
dsa.__version__

'1.22.2'

In [7]:
dsa.__version__

'1.22.2'

## Criando arrays com NumPy

In [8]:
arr1 = dsa.array([10,20,30,43,59,87,45,12,19,789,62,14,17,28,39])

In [9]:
print(arr1)

[ 10  20  30  43  59  87  45  12  19 789  62  14  17  28  39]


In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1.shape # tamanho

(15,)

In [12]:
arr1[4]

59

In [13]:
arr1[1:4] #indexação

array([20, 30, 43])

In [14]:
arr1[1:4+1]

array([20, 30, 43, 59])

In [15]:
# Criando uma lista de índices
indices = [1, 2, 5, 6]

In [16]:
arr1[indices] 

array([20, 30, 87, 45])

#### Criando máscara (padrão) para elementos

In [17]:
# máscara para elementos pares
mask = (arr1 % 2 == 0) #retorna pares

In [18]:
arr1[mask]

array([10, 20, 30, 12, 62, 14, 28])

In [19]:
mask

array([ True,  True,  True, False, False, False, False,  True, False,
       False,  True,  True, False,  True, False])

In [20]:
## Alterando um elemento do array
arr1[0] = 189

In [21]:
print(arr1)

[189  20  30  43  59  87  45  12  19 789  62  14  17  28  39]



# Não é possível misturar tipos de dados em array com NumPy

In [22]:
try:
    arr[0] = "Hoje acordei"
except:
    print("Não foi possível colocar String, pois o tipo de dado é int")
    

Não foi possível colocar String, pois o tipo de dado é int


In [23]:
try:
    arr1[0] = 99999
except:
    print("Não foi possível colocar String, pois o tipo de dado é int")
    
print(arr1)

[99999    20    30    43    59    87    45    12    19   789    62    14
    17    28    39]


# 

# Funções NumPy

In [24]:
# Função Array cria um array Numpy
arr2 = dsa.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [25]:
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
type(arr2)

numpy.ndarray

In [27]:
arr2.repeat(3)

array([ 1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10])

In [28]:
arr2.all()

True

In [29]:
arr2.cumsum() # soma acumulada dos elementos

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [30]:
arr2.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [31]:
arr3 = dsa.arange(0,50,5)

In [32]:
arr3

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [33]:
type(arr3)

numpy.ndarray

In [34]:
dsa.shape(arr3)

(10,)

In [35]:
print(arr3.dtype)

int32


In [36]:
#Criando arrays preenchidos por zero
arr4 = dsa.zeros(10)

In [37]:
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
# Retorna 1 nas posições em diagonal e 0 no restante
arr5 = dsa.eye(5)

In [39]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
# Os valores passados como parâmetros, formam uma diagonal

arr6 = dsa.diag(dsa.array([1, 2, 3, 4, 5])) #utilizando NumPy para criar outra lista NumPy


In [41]:
print(arr6)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [42]:
arr7 = dsa.array([True, True, False, False])

In [43]:
print(arr7)

[ True  True False False]


In [44]:
arr8 = dsa.array(["Alysson", "Roberto", "Vitória"])

In [45]:
print(arr8)

['Alysson' 'Roberto' 'Vitória']


#### função linspace() do NumPy é usada para criar sequência de números igualmente espaçados dentro de um intervalo 

In [46]:
print(dsa.linspace(0,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [47]:
print(dsa.linspace(0, 5, 10))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [48]:
print(dsa.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


# MATRIZES

In [49]:
arr9 = dsa.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
print(arr9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
print(arr9.shape)

(3, 3)


In [52]:
# Criando uma matriz 2x3 com números "1"
arr10 = dsa.ones((2,3))

In [53]:
arr10

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
# criando lista NumPy utilizando listas comuns
lista1 = [[13,48,95], [89,99,56], [58,96,32]]

In [55]:
arr11 = dsa.matrix(lista1)

In [56]:
type(arr11)

numpy.matrix

In [57]:
print(lista1)

[[13, 48, 95], [89, 99, 56], [58, 96, 32]]


In [58]:
print(arr11)

[[13 48 95]
 [89 99 56]
 [58 96 32]]


In [59]:
arr11.shape #Matriz 3x3 - 3 itens com 3 itens de profundidade

(3, 3)

In [60]:
arr11.size #

9

In [61]:
arr11[2,2]

32

In [62]:
lista1[2][2]

32

In [63]:
# indexação da matriz
arr11[0:2,2]

matrix([[95],
        [56]])

In [64]:
arr11[1,]

matrix([[89, 99, 56]])

In [65]:
arr11[1,2] = 89789

In [66]:
arr11

matrix([[   13,    48,    95],
        [   89,    99, 89789],
        [   58,    96,    32]])

In [67]:
## Forçando o tipo de dado com NumPy

x = dsa.array([1, 2])
y = dsa.array([2.3, 3.6])
z = dsa.array([1,3], dtype = dsa.float64) # Forçando a estrutura a ser float

In [68]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


In [69]:
z

array([1., 3.])

In [70]:
arr12 = dsa.array([[24, 76, 96], [12, 65, 9]], dtype = float)

In [71]:
arr12

array([[24., 76., 96.],
       [12., 65.,  9.]])

itemsize de array é atributo que retorna o tamanho em bytes de cada elemento de array


In [72]:
arr12.itemsize

8

In [73]:
arr12.nbytes

48

In [74]:
arr12.ndim

2

# Manipulando objetos de 3 e 4 dimensões com NumPy

In [75]:
arr_3d = dsa.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

In [76]:
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [77]:
arr_3d.shape # 2 linhas, 3 colunas e profundidade iguall a 4

(2, 3, 4)

In [78]:
arr_3d.size

24

In [79]:
arr_3d[1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [80]:
arr_3d[0,1,2]

7

In [81]:
arr_3d.ndim #Numero de dimensões

3

In [82]:
# Criando array de 4 dimensões

In [83]:
arr_4d = dsa.random.randint(low=0, high=10, size=(2, 4, 4, 5))

In [84]:
arr_4d

array([[[[3, 0, 6, 1, 9],
         [9, 1, 1, 1, 8],
         [2, 5, 0, 3, 2],
         [8, 7, 6, 3, 6]],

        [[9, 2, 0, 3, 7],
         [0, 5, 7, 9, 7],
         [8, 3, 7, 6, 8],
         [8, 7, 0, 8, 3]],

        [[9, 9, 6, 2, 7],
         [7, 8, 7, 0, 5],
         [5, 5, 7, 1, 4],
         [7, 1, 6, 7, 4]],

        [[8, 1, 0, 9, 2],
         [1, 3, 9, 8, 5],
         [8, 5, 1, 2, 1],
         [6, 2, 7, 3, 6]]],


       [[[2, 8, 4, 4, 8],
         [2, 9, 1, 8, 1],
         [8, 8, 6, 0, 0],
         [2, 0, 1, 5, 4]],

        [[8, 5, 5, 7, 6],
         [6, 3, 3, 2, 0],
         [2, 0, 8, 4, 1],
         [8, 9, 3, 2, 3]],

        [[2, 2, 7, 4, 3],
         [5, 4, 5, 1, 0],
         [6, 8, 0, 9, 8],
         [3, 9, 1, 3, 4]],

        [[9, 4, 3, 3, 2],
         [6, 4, 3, 0, 5],
         [6, 9, 5, 0, 3],
         [8, 8, 4, 7, 9]]]])

In [85]:
arr_4d.ndim # Numero de dimensões

4

In [86]:
arr_4d.shape

(2, 4, 4, 5)

In [87]:
arr_4d[1,2,3,0]

3

In [88]:
arr_4d[0,2,3,1]

1

# Manipulando arquivos com NumPy

In [ ]:
import os #pacote "os" para manipular o sistema operacional
filename = os.path.join('dataset.csv')

In [ ]:
with open("dataset.csv","r") as arquivo:
    print(arquivo.read())

In [ ]:
!more dataset.csv ## Somente para Jupyter notebook

In [ ]:
#Carregando um dataset para dentro de um array com NumPy

arr13 = dsa.loadtxt(filename, delimiter = ',', usecols = (0, 1, 2, 3), skiprows = 1)

'''Criando array do arquivo, tulizando Numpy
Por ser arquivo CSV, o delimitador são as vírgulas
"usecols" é utilizado para selecionar as colunas
Como NumPy só aceita 1 tipo de dado no array, então é necessário fazer esse filtro, 
pois a coluna nº 4 é de String
- Finaliza com "skiprows, para pular o primeiro indice, por ser String de cabecalho"
'''

In [ ]:
print(arr13)